site_name: discord-jsx-renderer
repo_url: https://github.com/deniz-blue/discordjsx
edit_uri: edit/main/docs/
theme:
  name: material
  palette: 
    scheme: slate
    primary: deep purple
    accent: indigo
  
  features:
    - content.action.edit
    - content.action.view
